### ISSUE TITLE
[BUG] - After update to version 8 Numbered bookmarks does not work any more if 'random' file is opened

### ISSUE THREAD

**Issue by Jarek300** [alefragnani/vscode-numbered-bookmarks#105]
Discussed [here](https://github.com/alefragnani/vscode-numbered-bookmarks/issues/97).

Release 8.0.3:

![image](https://user-images.githubusercontent.com/10242002/114346706-2e415300-9b64-11eb-95e0-79624f9b1726.png)

**Comment by alefragnani** [comment]
Hi @Jarek300 ,

First of all, sorry for the delay. About the issue, are you using the same scenario from previous issue? The update didn’t made any difference for you?

Based on your print, it doesn’t say anything about the extension (error message or something like that). Do you have more details/log to share?

Thank you

**Comment by Jarek300** [comment]
I've upgraded to version 8.1 and extension works correctly with ''random' files.

Thanks!
