### ISSUE TITLE
[QUESTION] - differences between extensions

### ISSUE THREAD

**Issue by lonix1** [alefragnani/vscode-numbered-bookmarks#114]
@alefragnani I just discovered your extensions.

Are the [alefragnani.numbered-bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks) and [alefragnani.Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) extensions the same, except one has numbers?

Are there any other differences?

Thank you for these very nice extensions!

**Comment by alefragnani** [comment]
Hi @lonix1 ,

No, these are two different extensions, but with the same purpose (quick navigation). The more advanced (with more features) and which receives more updates is the Bookmarks extension. You have a Side Bar, Selection (not only jump) and Labeled bookmarks. Sooner you will have Tags too. This one is based on the Bookmarks feature from Delphi IDE/Language, which used to be my main development language.

You can easily look for the differences (and how they work) looking at their README files. It describes all features, settings and commands you have available.

Hope this helps

**Comment by lonix1** [comment]
Thanks for the detailed explanation.

Out of curiosity, why not add numbers to the other extension, and then just have one extension to maintain, with all the features?

**Comment by alefragnani** [comment]
Because this small difference makes the whole difference on how the extension work and its usability. Besides, this one is more like a Delphi way of Bookmarks, which is way simpler.
