### ISSUE TITLE
Key binding

### ISSUE THREAD

**Issue by v-andrew** [alefragnani/vscode-numbered-bookmarks#12]
<Ctrl>+1, <Ctrl>+2, <Ctrl>+3 are used to switch between editor views, so plugin destroys this functionality.

Please add configuration parameter to free <Ctrl>+1, <Ctrl>+2, <Ctrl>+3 so it could be used by VSCode Views.

**Comment by alefragnani** [comment]
Hi @v-andrew ,

Unfortunately there is no way to add _parameters_ to turn on/off keybindings. Once you define in the extension, it will be used. 

But you can _customize keybindings_ in VS Code, so you could change the keybindings for _switching groups_ to other than `Ctrl + 1 / 2 / 3` or even remove the keybindings from the extension as well, using `-` in front of it. It would be something like:

```json
{ 
  "key": "Ctrl+1", 
  "command": "-numberedBookmarks.jumpToBookmark1", 
  "when": "editorTextFocus"
}
```

In fact, when I released the extension, there was no conflict in keybindings. I guess VS Code added the same keybindings just when Tabs were added, when the _editor group/stack_ concept appeared.

Hope this helps
