### ISSUE TITLE
[FEATURE] - Keep bookmarks after Rename and Save As ...

### ISSUE THREAD

**Issue by ethsol** [alefragnani/vscode-numbered-bookmarks#120]
Hi Alessandro,

  I suggest to reserve bookmarks after file name change, ie. after _Save as..._ changes the file name.
Numbered Bookmarks 8.1.0 loses all the bookmarks after file name change.

Thanks
BR,
Laszlo

**Comment by alefragnani** [comment]
Just noticed these are two different scenarios:

* `File Rename`:  the same as https://github.com/alefragnani/vscode-bookmarks/issues/209 )
* `File: Save As`: a new file (copy of a previously selected/focused) is created. 

I don't know about a `File: Save As` event/api, so depends on that do properly support it. 

The `File Rename` event, on the other hand, is already in the works.

**Comment by alefragnani** [comment]
`File: Save As` depends on https://github.com/microsoft/vscode/issues/146864
