### ISSUE TITLE
[FEATURE] - Alternative Shortcut for Mac (Cmd-Shift-3 and Cmd-Shift-4)

### ISSUE THREAD

**Issue by marlonbragaleite** [alefragnani/vscode-numbered-bookmarks#127]
This plugin is awesome, but since #3 and #4 is not functional in a Mac, since this is already been used by the system, I end up using only 1 and 2 as bookmarks.

I wonder if there could be any shotcut alternative to make all numbers available as shortcuts to toggle the bookmarks.

**Comment by alefragnani** [comment]
Hi @marlonbragaleite ,

Yes, you can customize any shortcut. Simply follow VS Code documentation https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor. It works not only for extension’s shortcuts, but also VS Code built in commands.

Hope this helps
