### ISSUE TITLE
Remember bookmarks across sessions

### ISSUE THREAD

**Issue by schnesim** [alefragnani/vscode-numbered-bookmarks#13]
It would be great to have the feature of remembering bookmarks. So when I quit VSCode and restart it, all the previously added bookmarks are still there.

**Comment by alefragnani** [comment]
Hi @schnesim ,

You already have that. Just add `"numberedBookmarks.saveBookmarksBetweenSessions": true` to you **User settings**.

Take a look at the `readme` for more information 

Hope this helps
