### ISSUE TITLE
[FEATURE] - Allow jump to bookmark across files

### ISSUE THREAD

**Issue by dudeNumber4** [alefragnani/vscode-numbered-bookmarks#132]
Currently if you have multiple files with bookmarks, you have to invoke the "List from all files" command to navigate to your bookmarks.  Even then, you don't see the numbers, just a line of code.
It would be so much better just to invoke the "Jump to Bookmark" command with the appropriate number to jump to any bookmark in any open file.  As it is, it's not really all that helpful.

**Comment by alefragnani** [comment]
Hi @dudeNumber4 ,

If you want to jump to some specific Bookmark Number, no matter the file it is, you should take a look take a look at `numberedBookmarks.navigateThroughAllFiles` setting. 

By the docs:

### Possible Values:

Value | Explanation
--------- | ---------
`false` | _default_ - same behavior as today
`replace` | you can't have the same numbered bookmark in different files
`allowDuplicates` | you can have the same numbered bookmark in different files, and if you jump repeatedly to the same number, it will look on other files

I guess `allowDuplicates` would fit your needs

Hope this helps

**Comment by alefragnani** [comment]
Glad to hear @Code6226 .

I don’t have too much experience with IntelliJ. Just started using Rider a while ago.

This extension was developed based on Delphi bookmarks, because it was the IDE I was using back then.
