### ISSUE TITLE
[QUESTION] - List from All Files order

### ISSUE THREAD

**Issue by Bjorn-Eric-Abr** [alefragnani/vscode-numbered-bookmarks#135]
Hi! And thanks for an awesome plugin!

When using the `List from All Files` command - in what order are the bookmarks listed? It would be nice to have some visual representation, listing the bookmarks 0-9.

**Comment by alefragnani** [comment]
Hi @Bjorn-Eric-Abr ,

First of all, thank you for your kind words. I’m glad to know the extension is being helpful.

The bookmarks are listed, for each file, from 0 to 9. About the files, it starts with the current file and then, ordered by (time) the files that some bookmark where toggled . Which means it does not follow alphabetical order.

How do you imagine to have the 0-9 numbering displayed in the list? The downside is, there is no way to add a glyph, unfortunately 😞 .

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
