### ISSUE TITLE
[FEATURE] - Make available in VS Code Online version

### ISSUE THREAD

**Issue by cssyphus** [alefragnani/vscode-numbered-bookmarks#154]
Will you be updating your two bookmark extensions so that they work in VS Code online? (vscode.dev)  At this time, both of your bookmark extensions are unavailable for use in VS Code online.

See this image: [https://imgur.com/a/xZShMkE](https://imgur.com/a/xZShMkE)

**Comment by alefragnani** [comment]
Hi @cssyphus ,

Yes, it is being tracked in #130 

Thanks for reporting
