### ISSUE TITLE
[FEATURE] - Support toggle between bookmarks in different files

### ISSUE THREAD

**Issue by ty4git** [alefragnani/vscode-numbered-bookmarks#155]
Good afternoon.
Could you please add possibility of toggle between bookmarks in different files by hotkey (ex. ctrl + 1). It would be very nice and useful.
For example there is bookmark 1 in file 1, and file 2 is active right now. After pressing of hotkey for bookmark 1 the file 1 will be active.

**Comment by alefragnani** [comment]
Hi @ty4git ,

You could play with the `numberedBookmarks.navigateThroughAllFiles` setting. 

Maybe the best fit for your scenario could be:

```json
    "numberedBookmarks.navigateThroughAllFiles": "allowDuplicates"
```

Possible Values:

Value | Explanation
--------- | ---------
`false` | _default_ - same behavior as today
`replace` | you can't have the same numbered bookmark in different files
`allowDuplicates` | you can have the same numbered bookmark in different files, and if you jump repeatedly to the same number, it will look on other files

More info here https://github.com/alefragnani/vscode-numbered-bookmarks#available-settings

Hope this helps
