### ISSUE TITLE
[FEATURE] - README, add installation steps for VS Codium

### ISSUE THREAD

**Issue by Trikenstein** [alefragnani/vscode-numbered-bookmarks#160]
Using VSCodium v1.77.0 searching in extensions by keyword "Numbered Bookmarks" doesn't show this extensions. In case it is compatible with VSCodium. Would appreciate you add an installation section in the README to show how to install it in VSCode and VSCodium in particular.

Searching for Bookmark extension within VSCodium, the closest is your other extension [Bookmarks v13.0.1](https://github.com/alefragnani/vscode-bookmarks). Not sure if this is a replacement to the "Numbered Bookmarks".

**Comment by alefragnani** [comment]
Hi @Trikenstein ,

The extension will be published on open-vsx, which is the default extension gallery used by VS Codium. I hope this could happen in a couple of weeks. Doing so, the installation process will be similar to VS Code itself.

This is already being tracked in #147. Stay tuned.

Hope this helps
