### ISSUE TITLE
[FEATURE] - Simple new command: "Numberd Bookmarks: Add next free Bookmark-Number"

### ISSUE THREAD

**Issue by schittli** [alefragnani/vscode-numbered-bookmarks#161]
Hello

**thank you very much for sharing your great work.**

I have a small but useful suggestion:
While working on code, I often have to set important bookmarks, because I later will have to do important work on those positions, e.g. write a unit test, test some code because it smells, or add a forgotten switch case statement.
These bookmarks are different from normal bookmarks because I don't want to _maybe_ jump there again, but need a list to work through later.
- I usually have less than 10 "ad-hoc tasks", so numbered bookmarks are very suitable.
- In this situation, the bookmark number is not important, but only the list as a whole.

Therefore it would be ingenious if you could offer a command like "Add free numbered bookmark" which searches itself for the first free numbered bookmark and adds it to the position.

This would allow us to mark important positions very fast 😀 

Thanks a lot, kind regards,
Thomas

**Comment by alefragnani** [comment]
Hi @schittli ,

A similar request has already been made in #152, so I think you could take a look and contribute there.

Hope this helps
