### ISSUE TITLE
[FEATURE] - While adding a new numbered bookmark: Make visible which numbers are free / used

### ISSUE THREAD

**Issue by schittli** [alefragnani/vscode-numbered-bookmarks#162]
Hello

If one would like to add a new bookmark number, one must know which ones are used / free.
Therefore one needs a view to see all numbered bookmarks and because (I guess) there is no View / Panel, one has to:
1. Use the command `numberedBookmarks.list` to see the used numbers and select a free number
2. Use another command to add a new numbered bookmark

It would be useful if those commands could display if the bookmark is used / free:
![image](https://user-images.githubusercontent.com/8282673/233030321-78ea5f8a-1cf3-46d0-8cb6-7ce13d26f6f0.png)

Thanks a lot, kind regards,
Thomas

**Comment by alefragnani** [comment]
Hi @schittli ,

Every command in VS Code must be _declared_ upfront, and can't have its title _edited_ in runtime. The Command Palette also doesn't support _disabled_ commands, which means that every visible command is "runnable". Context Menus, on the other hand, support _disabled_ state.

That being said, there are two possible alternatives for this:

* Remove _allocated_ numbered bookmarks from Command Palette / Context Menu
* Add a ✔️  symbol to the _allocated_ numbered bookmarks.

Hope this helps

**Comment by alefragnani** [comment]
Just find out GitHub Discussions now support **Pools**. 
Let's see how it works 😬 

https://github.com/alefragnani/vscode-numbered-bookmarks/discussions/164

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added nor its poll receive enough votes.

Thanks for your understanding
