### ISSUE TITLE
Toggle Bookmarks 1 on big file

### ISSUE THREAD

**Issue by luzdegan** [alefragnani/vscode-numbered-bookmarks#17]
Hello,

If I run the "Numbered Bookmarks: Toggle Bookmarks 1" function inside a big file, i get the following error:

> Running the contributed command:'numberedBookmarks.toggleBookmark1' failed. 

and no bookmark is set. The file has 161864 text lines. On smaller files it works.

It is something wrong for big files?

Version in use: 0.6.0 

Best Regards,

Luz

**Comment by alefragnani** [comment]
Hi @luzdegan ,

Yes, there is a _limitation_  for large files in VSCode. A similar issue was reported on my other extension https://github.com/alefragnani/vscode-bookmarks/issues/31 sometime ago. The error was a bit different, but I remember seeing the same error while playing with larger file limits, like yours.

Unfortunately it seems _as designed _ by VSCode team right now. Maybe in the future they review this limits.

Hope this helps
