### ISSUE TITLE
[FEATURE] - Keep bookmark even when associated line is deleted

### ISSUE THREAD

**Issue by tgaochn** [alefragnani/vscode-numbered-bookmarks#170]
Hi,

Thanks for the great tool! It's super helpful in my work.
I was wondering whether we can keep the bookmark even when the associated line is deleted. 
The same feature has been implemented in [vscode-bookmarks](https://github.com/alefragnani/vscode-bookmarks/issues/503).
Thanks a lot!

Best

**Comment by alefragnani** [comment]
Hi @tgaochn ,

This feature was originally released here, in #27. So, you just have to play with the `numberedBookmarks.keepBookmarksOnLineDelete` setting.

More details here  https://github.com/alefragnani/vscode-numbered-bookmarks/issues/27#issuecomment-1021743169.

Hope this helps

**Comment by tgaochn** [comment]
Oh, I didn't realize that it was already there. Thanks for the info.
