### ISSUE TITLE
Can't navigate to bookmark in file outside of project

### ISSUE THREAD

**Issue by dudeNumber4** [alefragnani/vscode-numbered-bookmarks#171]
Type: <b>Bug</b>

1. Open a project folder.
2. Open a file that lives outside the project folder on a different drive
3. Set bookmark #1 on a file within the project folder
4. Set bookmark #2 on the file that lives outside project folder
5. Navigate to bookmark 1
6. Navigate to bookmark 2 using command pallette.
7. Error:
Command 'Numbered Bookmarks: Jump to Bookmark 2' resulted in an error 
cannot open 
….:///c%3A/d%%3A/  …….
Detail: Unable to read file 
(Error: Unable to resolve nonexistent file  ..........

Extension version: 8.4.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (4.70GB free)|
|Process Argv|--crash-reporter-id 35a7a4f0-74bd-4784-8842-35e4a50cf04e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30991134
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30992952
666c4381:30973075
gee8j676:30988843

```

</details>

**Comment by alefragnani** [comment]
Hi @dudeNumber4 ,

This is caused by the same issue as #148, and the fix should apply to both scenarios.

Hope this helps
