### ISSUE TITLE
[FEATURE] - Exclude certain numbers to allow toggle line comment on Mac on certain keyboards

### ISSUE THREAD

**Issue by simonhuwiler** [alefragnani/vscode-numbered-bookmarks#172]
Hi there

I'm an old Delphi user, so I like this extension. On Mac with the Swiss keyboard layout, however, there is a major problem:
The Slash (`[/]`) is located on the `[7]` key. The shortcut to comment out lines (`[cmd] + [/]` or `[cmd] + [7]`) no longer works after installing this extension. And this shortcut is of course quite important. Is there a way to work around this - for example, by excluding certain numbers?

Best regards,
Simon

**Comment by alefragnani** [comment]
Hi @simonhuwiler ,

I'm sorry to know that. MacOS is really not Delphi friendly, as other native commands also conflict with the Bookmarks, like the screenshot commands.

And yes, you can remove any keyboard shortcut, simply using the this tip (https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule). 

Hope this helps

**Comment by simonhuwiler** [comment]
Thank you @alefragnani 
I am not familiar with this: Can I remove a keybinding for your plugin with this method or just for vscode? I d'like to leave `Cmd` + `Shift` + `7` as default (toggle comment), all the other numbers would be great to have them as bookmark numbers.

**Comment by alefragnani** [comment]
Hi @simonhuwiler ,

This method works for any keybinding, on any extension, and even on VS Code native commands. You can remove or reassign any keybinding, at your will. Take a closer look on that documentation and you will see that VS Code even has a [ detect conflict](https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts) feature to help you identify which commands defines the same keybinding.

Hope this helps

**Comment by simonhuwiler** [comment]
Ah, thats fantastic! Thanks for your help!
