### ISSUE TITLE
[BUG] - Cannot make a bookmark in large files

### ISSUE THREAD

**Issue by Cuperido** [alefragnani/vscode-numbered-bookmarks#173]
There is a bug causing errors in large-sized files.

**Environment/version**

- Extension version: 8.4.0
- VSCode version: 1.84.2
- OS version: Windows 11

**Steps to reproduce**

1. Load a large text file. A 100mb size with 100,000 lines is enough to reenact.
2. When I try to add a bookmark, the editor shows a pop-up with the `Cannot read properties of undefined (reading 'selection')` error message.
3. You must read the file from the disk to reenact the bug. It works fine when it's pasted from the clipboard into the editor.

Thank you

**Comment by alefragnani** [comment]
Hi @Cuperido ,

Yes, there is a _limitation_  for large files in VSCode. A similar issue was reported in #17 sometime ago. The error was a bit different, but I remember seeing the same error while playing with larger file limits, like yours.

Unfortunately it seems _as designed _ by VSCode team right now. Maybe in the future they review this limits.

Hope this helps
