### ISSUE TITLE
[FEATURE] - Global bookmarks

### ISSUE THREAD

**Issue by T04435** [alefragnani/vscode-numbered-bookmarks#179]
The current implementation of this plugin allows to add/go to a bookmarked lines within a file.

I would like to have a way to set bookmarks(0-9) on any file and go to any bookmark in any file.

file 1
book 0

file 2
book 3

file 3
book 2

So no matter in which file I'm at I want to hit the command and go to book # open file #

**Comment by alefragnani** [comment]
Hi @T04435 ,

I guess you just have to play with the `navigateThroughAllFiles` setting. Define this on your user settings:

```json
        "numberedBookmarks.navigateThroughAllFiles": replace
```

More info in the README file https://github.com/alefragnani/vscode-numbered-bookmarks#available-settings

Hope this helps

**Comment by T04435** [comment]
@alefragnani Awesome mate this just worked.

I should have read the docs more thoroughly 😅
