### ISSUE TITLE
Numbering only works up to 2?

### ISSUE THREAD

**Issue by puruzio** [alefragnani/vscode-numbered-bookmarks#22]
In using Numbered Booksmarks, Cmd+(Shift)+# for assigning and jumping to bookmarks work for 1 & 2 only, but not 3 or higher.  Am I missing something?

I'm on OSX 10 and VS Code 1.11.2. Thanks for your help!

**Comment by alefragnani** [comment]
Hi @puruzio ,

It should have 1..0, with keybinding for 1..9 (because `ctrl + shift + 0` appears to be blocked by OS. 

Maybe you are having an issue caused by with the new keybindings system released in VSCode 1.11 (https://github.com/alefragnani/vscode-bookmarks/issues/63)

Hope this helps

**Comment by alefragnani** [comment]
Hi @puruzio , any news about it? Do you still have issues?

**Comment by puruzio** [comment]
Yes, I still have the same issue.

**Comment by alefragnani** [comment]
Could you check your `Keyboard Shortcuts` and see if there is any other command with the same keybinding? Also, the commands itself (`Numbered Bookmarks: Toggle Bookmark 3`), instead of the keybinding, does work?

**Comment by puruzio** [comment]
The command itself works. I don't see any other keyboard shortcut sharing the same key combination. :(

**Comment by alefragnani** [comment]
Did you check if your problem is related to this https://github.com/alefragnani/vscode-bookmarks/issues/63? Also, when you say that _the command itself works_, it means that the bookmark image is displayed at the gutter too?

You could open `Toggle Developer Tools` and look in `Console` if any error message is being displayed.

**Comment by puruzio** [comment]
Turned out there were Mac OS default key binding for shift+command+3 & 4 for screen capturing. Turning it off seems to solve the problem. Thanks for looking into this.
