### ISSUE TITLE
Sticky discussion

### ISSUE THREAD

**Issue by danseethaler** [alefragnani/vscode-numbered-bookmarks#29]
Hey @alefragnani!

I wanted to reach out and ask about the `Sticky` class in this extension. I'm developing a VSCode extension that allows users to tab through their multiple cursors/selections and edit each one individually. The challenge is of course if the user adds a new line, deletes a line, etc while iterating over the selections.

In Atom handling this is a cinch with [markers](https://atom.io/docs/api/v0.208.0/Marker). I'm surprised that VSCode doesn't have anything comparable. After reading your `Sticky` class it looks like you've had to implement this functionality yourself. So I'm just curious if you've been part of any discussion in the community about adding this functionality to VSCode core or if you have any tips on implementing this in another package.

Thanks for any feedback and for a great extension!

**Comment by alefragnani** [comment]
Hi @danseethaler ,

First of all, sorry for taking so long to answer you. It's been a busy week 😭 .

In fact, I have to give credits to @terminux, the original developer of this feature in my Bookmarks extension (https://github.com/alefragnani/vscode-bookmarks/pull/20). I just helped him with fixes and updates, but the core is his. 

About the API, yes, it seems VS Code don't have the same approach as Atom (which I also looked when creating my extension). At the time, I didn't ask VS Code team about extending the API, and also didn't searched for alternatives anymore. 

The core concept is simple, it looks for data in `contentChanges`, to decide which kind of change has been made. You just have to take care of _some points_, which you will find mapped in the extension (some are also commented 😄 ).

Feel free to use the extension's source. If you have any question, or need any help, just let me know. If your extension is public, I could fork to help you.

Hope this helps

**Comment by danseethaler** [comment]
Thanks @alefragnani for your feedback! That's really helpful to get a sense of how this has evolved. I'll try to spend some time this week implementing this class and continue the community discussion around this feature. I almost wonder if an npm package implementing this functionality would help isolate the logic and make it more accessible. I'll let you know what I find.

Thanks again!
