### ISSUE TITLE
Installed extension and I couldn't reliably "Move Line Up" anymore

### ISSUE THREAD

**Issue by darkvertex** [alefragnani/vscode-numbered-bookmarks#31]
For some reason, after installing this extension (which looks great btw!) when I select some lines and move up, my line selection gets fucked with and if I keep trying to move up, it mangles all my code.

If I uninstall the extension, my selecting and moving of line blocks works like a charm again. Maybe it's a clash with one of my other extensions but I don't know.

See below the strange behaviour...
![peek 2017-12-08 12-50 optimized](https://user-images.githubusercontent.com/941331/33778550-30ab863e-dc17-11e7-9dd5-72ee6425d78b.gif)
- The green flashing is the https://github.com/richie5um/vscode-snake-trail extension which indicates changed text.
- All I'm doing is Ctrl+L to select a few lines in an indented block and then Ctrl+Shift+UpArrow a couple of items, and on each time I tap the UpArrow while holding Ctrl+Shift, my selection is being modified, so every time it moves up, it moves differently.

Any ideas? Would love to use them bookmarks. :)

**Comment by alefragnani** [comment]
Hi @darkvertex ,

That's really weird! At first sight, I don't see why installing the extension would make this with your code. I don't change the text (just the bookmark position), and it would do that, only if you have at least one bookmark defined in the document.

I will take a closer look at the extension's source, to see if I missed something, and let you know.

**Comment by darkvertex** [comment]
Do you know if there is an easy way to temporarily disable all VSCode extensions such that I could enable them one by one to find out whether one, in particular, is fighting yours?

I saw there's a `--disable-extensions` commandline flag, but the problem is it disables them completely to the point I can't even enable them, so not very useful for this use case.

**Comment by alefragnani** [comment]
You could try to _disable_ all extensions, right in the **Extensions** panel. Then you enable one at a time, until you reproduce the issue.

Please, let me know if you have any news about...

**Comment by alefragnani** [comment]
@darkvertex , any news about it?
