### ISSUE TITLE
Can't toggle bookmarks 1 and 2 with hotkeys

### ISSUE THREAD

**Issue by EwgB** [alefragnani/vscode-numbered-bookmarks#32]
I can't toggle the bookmarks number 1 and 2 with the hotkeys (Ctrl+Shift+1/2). I can toggle them with the "Quick Open" menu (Ctrl+P), I can navigate to them with Ctrl+1/2 once set. I can also toggle all the other bookmarks normally.

**Comment by alefragnani** [comment]
Hi @EwgB ,

First of all, sorry for taking so long to answer you.

Does it shows the keybinding in Command Palette? Also, do you remember any other installed extension that could have the same keybinding?

I noted that there is a _core_ command `editor.action.replaceOne` which uses `Ctrl + Shift + 1`, but no other command for `2`. You could open the keybindings file (`Open Keyboard Shortcuts File`) and search for other commands that conflicts. It will list all commands, from all installed extensions.

Hope this helps

**Comment by EwgB** [comment]
Hi @alefragnani !

I have checked the active shortcuts, as you advised. There is indeed the one you mentioned for `Ctrl + Shift + 1`, and even another one, `search.action.replace`. But there isn't one for `Ctrl + Shift + 2`. Both commands show up in the command palette.

**Comment by alefragnani** [comment]
Hi @EwgB ,

I think there is some issues in recent VS Code releases, related to keybinding conflicts. It appears it is not respecting the _defined sequence_ when resolving conflicts. I'm having a similar issue on other extension, in this case, a _Keymap extension_ which should _override_ the default keybindings_ but isn't.

You could try to _turn off_ the conflict command. To do so, you should add `-` in front of the command, as documented here https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

Hope this helps

**Comment by EwgB** [comment]
It seems that my problem is not with the extension, since the aforementioned hotkeys don't work in the Deplhi IDE, too. It has to be some Windows-global hotkey issue. Thanks for your help, @alefragnani!
