### ISSUE TITLE
Issue with Line Up and Line Down

### ISSUE THREAD

**Issue by hosseinahm** [alefragnani/vscode-numbered-bookmarks#36]
In my editor, when I use Move Line UP/Down and have this extension enabled, selected line moves up/down but the selection doesn't move with that and remains at its old position.

**Comment by alefragnani** [comment]
Hi @hosseinahm ,

Is there anything similar to #31? Another user has reported, but didn't give me much more information to reproduce, so I closed the issue.

Hope this helps
