### ISSUE TITLE
Bookmarks are deleted on saving a file.

### ISSUE THREAD

**Issue by cydside** [alefragnani/vscode-numbered-bookmarks#38]
Hi,
first of all thanks for you nice software. I'm facing the following issue:

System:
>     4.13.0-37-generic GNU/Linux
>     Distributor ID: LinuxMint
>     Release: 18.3
>     Codename: sylvia

VSCODE:
> Versione 1.24.1
> Commit 24f62626b222e9a8313213fb64b10d741a326288
> Data 2018-06-13T17:47:35.732Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Nodo 7.9.0
> Architettura x64

It happens that on saving the current file all the bookmarks associated are deleted!

**Comment by alefragnani** [comment]
Hi @cydside ,

I'm sorry for taking so long to answer you. 

Are you still having this issue? If yes, do you have any other extension that does some _post-processing_ in your files, like a formatter/prettier?

Hope this helps

**Comment by cydside** [comment]
No, just checked, I'm not having this issue anymore. I've Beautify 1.3.2 installed.

Thanks.
