### ISSUE TITLE
bug: bookmark removes on undo

### ISSUE THREAD

**Issue by darkstarx** [alefragnani/vscode-numbered-bookmarks#47]
1. Set bookmark in line.
2. Make changes in line.
3. Undo changes by pushing ctrl-z (cmd-z on mac) until bookmark gone down on the next line (BUG №1)
4. Process undo changes by pushing more times ctrl-z (cmd-z on mac). Bookmark disappears (BUG №2).

**Comment by alefragnani** [comment]
Hi @darkstarx ,

This is probably related to the issue from my other [Bookmarks](
https://github.com/alefragnani/vscode-bookmarks/issues/116) extension. 

I hope I could take a look at these in the coming weeks, but first, I have a few priority features/issues to release.

Hope this helps
