### ISSUE TITLE
Cut text issue: selection still exist after cutting

### ISSUE THREAD

**Issue by Daijobou** [alefragnani/vscode-numbered-bookmarks#48]
I have a strange issue with this extension.
![vscodeg](https://user-images.githubusercontent.com/260343/50821819-755e8f00-1330-11e9-8d7d-d4c91f3fa776.gif)
As you can see, after cut a line, its select a other line. This happen only with this extension is enabled.  I have only this single extension enabled. Can someone confirm this?

step1. Insert this code in a new tab:
```
if ()
{
text text text
text text text
text text text
text text text
```
step2. Set cursor after "{" and press return. It should create a new line with tabulator
step3. Go with mouse to beginning of first "text text text"-line
step4. Selected this line with SHIFT+CURSOR DOWN
step5. Press SHIFT+DEL or CTRL+X for cut line

Now the line is removed, but the selection of this removed line jumps down to line second "text text text"-line. That happen only one time after step 2. All cuts after the first cut working fine.

AND this happen only in new created tabs in this session and tabs that was saved. After restart vscode existing "new tabs" dont show this issue. Again now only new created "new tabs" and already saved tabs. So this issue its little strange.

I use windows 10.

**Comment by alefragnani** [comment]
Hi @Daijobou ,

Have you experienced this issue with no extensions enabled? You can do that if you open Code via command line `code --disable-extensions <somefolder>`.

I don't think this issue is caused by the extension, because the extension itself does not manipulate selection areas, unless you have some bookmark defined in the document.  

I remember seeing a similar behavior while moving (more than one) lines up and down, and in this case, it was a VS Code issue, not from any extension. Please, take a look at VS Code repo. Maybe someone else also found this issue.

Hope this helps.

**Comment by alefragnani** [comment]
Of course I tested, that’s why I asked 😁 .  A lot of times people say there is an issue with the extension, but the reason is VSCode itself. Simply forgetting to test without the extension.

I’ll double check for possible changes in text selection, without bookmarks in the document. Maybe I have missed something.

**Comment by alefragnani** [comment]
@Daijobou I have noted two different things, from my settings, on your scenario. 

First, you don't seem to have _auto-suggestion_ enabled. After I type the first `line1`, every new line that I start typing, VS Code _suggests_ `line1` again
Second, when you type `(` or `{`, it is not auto-suggesting _the closer_.

I'm not saying _that's the reason_, but something is different.

Have you changed anything about it in VS Code settings?

**Comment by Daijobou** [comment]
I don't like auto-suggestion, so I have disabled it, but the error exists already long time before disable this settings.

Thats my setting

> {
>     "files.trimTrailingWhitespace": true,
>     "editor.wordWrap": "on",
>     "php.validate.enable": false,
>     "explorer.autoReveal": false,
>     "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
>     "window.title": "${dirty}${activeEditorMedium}${separator}${rootName}${separator}${appName}",
>     "files.exclude": {
>         "**/.git": true,
>         "**/.svn": true,
>         "**/.hg": true,
>         "**/CVS": true,
>         "**/.DS_Store": true,
>         "**/*.png": true,
>         "**/*.jpg": true,
>         "**/*.7z": true,
>         "**/*.gz": true,
>     },
>     "workbench.colorTheme": "Atom One Dark",
>     "typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
>     "typescript.format.placeOpenBraceOnNewLineForFunctions": true,
>     // https://stackoverflow.com/questions/49942726/visual-studio-code-n-in-regex-file-search-not-supported
>     "search.useRipgrep": false,
>     "workbench.editor.highlightModifiedTabs": true,
>     "editor.suggestOnTriggerCharacters": false,
>     "php.suggest.basic": false,
>     "html.suggest.html5": false,
>     "editor.acceptSuggestionOnCommitCharacter": false,
>     "editor.acceptSuggestionOnEnter": "off",
>     "editor.suggest.filterGraceful": false,
>     "editor.suggest.snippetsPreventQuickSuggestions": false,
>     "javascript.suggestionActions.enabled": false,
>     "typescript.suggestionActions.enabled": false,
>     "emmet.showAbbreviationSuggestions": false,
>     "jsDocCompletion.enabled": false,
>     "javascript.suggest.names": false,
>     "javascript.suggest.paths": false,
>     "javascript.suggest.autoImports": false,
>     "typescript.suggest.paths": false,
>     "typescript.suggest.autoImports": false,
>     "javascript.suggest.enabled": false,
>     "editor.quickSuggestionsDelay": 100000,
>     "javascript.autoClosingTags": false,
>     "typescript.autoClosingTags": false,
>     "html.autoClosingTags": false,
>     "editor.autoClosingBrackets": "never",
>     "editor.autoClosingQuotes": "never",
> }

**Comment by Daijobou** [comment]
Maybe this hint helps you. That problem only happen, when I press return and created a new line with tab. Thats have nothing to do with "{" or "(". See this version
![vscodel](https://user-images.githubusercontent.com/260343/51392112-4b794980-1b34-11e9-891f-39be069783d9.gif)

**Comment by Daijobou** [comment]
Any news here? Its still wrong labeled as a question and vscode.

**Comment by alefragnani** [comment]
Hi @Daijobou ,

No news. After those unsuccessful tests, I had other priorities to look at, sorry. 

About the labels, it remains as it was because I didn't make more tests, so there was no reason to update them. 

I hope I could revisit this issue in the next week. Stay tuned.

**Comment by Daijobou** [comment]
Great work! Thank you very much to fix this issue :)
