### ISSUE TITLE
Feature request: manage bookmark number automatically

### ISSUE THREAD

**Issue by hypeaches** [alefragnani/vscode-numbered-bookmarks#49]
User could use a only shotcut key to add bookmark, without attention to bookmark number. The bookmark number could manage automatically.

**Comment by alefragnani** [comment]
Hi @hypeaches ,

If you don’t want to care which number you assigned to the bookmarks, I think you could take a look at my other [Bookmarks](
https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) extension. It’s not limited to 10 bookmarks _per file_ as this one, so you don’t have to worry about that as well.

Hope this helps
