### ISSUE TITLE
doesnt work on new installation

### ISSUE THREAD

**Issue by nickblock** [alefragnani/vscode-numbered-bookmarks#50]
Installed the plugin, fedora 29, vscode 1.30, existing workspace.
Plugin says it's enabled. 
When I use any shortcut eg ctrl-alt-k a message pops up saying "command bookmarks.toggle not found.

**Comment by alefragnani** [comment]
Hi @nickblock ,

This error happened on my othe Bookmarks extension, was reported in 
https://github.com/alefragnani/vscode-bookmarks/issues/178, and was fixed a few hours ago. 

Please, update the extension to 10.2.2

Hope this helps

**Comment by nickblock** [comment]
started working after some restarting
