### ISSUE TITLE
Allow bookmark to reference exact cursor position

### ISSUE THREAD

**Issue by ViktorQvarfordt** [alefragnani/vscode-numbered-bookmarks#51]
Currently, a bookmark references a line. I request the feature that a bookmark references line _and column_. In this way, when jumping to a bookmark, you end up at exactly the position where you created the bookmark. This would significantly improve my workflow.

**Comment by alefragnani** [comment]
Hi @ViktorQvarfordt ,

This is already being tracked in #14. And as you can see, it's on the roadmap in the next milestone.

Hope this helps

**Comment by ViktorQvarfordt** [comment]
Awesome. I missed that. Thank you!
