### ISSUE TITLE
'what's new' page needs to be made dark-theme friendly

### ISSUE THREAD

**Issue by Matt4880** [alefragnani/vscode-numbered-bookmarks#57]
The 'what's new' page on plugin upgrade is currently not styled well for dark themes - lots of black text and the colours don't look great

(theme used βUI - one dark https://www.vscolors.com/theme/4faf18987a5b5bfe6ffb3361310d557e)

![image](https://user-images.githubusercontent.com/23239416/63598472-873b2c80-c5b7-11e9-841a-0bb752544a58.png)

**Comment by alefragnani** [comment]
Hi @Matt4880 ,

Unless something _has returned_ from VS Code itself, this issue has been fixed in version 6.1.1, released in March/2019, as described in changelog

> **[6.1.1] - 2019-03-15**
> **Fixed**
>   *  What's New page broken in VS Code 1.32 due to CSS API changes

Which VS Code, extension version, and OS are you using?

Hope this helps

**Comment by Matt4880** [comment]
This is a bit problematic as I use around 3 dev machines - tried on 2 of them and the colours actually look OK there. It's possible that I saw this on a machine that I'd not used in a while that was halfway through updating VSCode and extensions.

Seen it working fine on 2 machines that are fully up-to-date now though
