### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dadams63** [alefragnani/vscode-numbered-bookmarks#60]
- Issue Type: `Bug`
- Extension Name: `numbered-bookmarks`
- Extension Version: `6.2.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 5,
		"activateCallTime": 0,
		"activateResolvedTime": 11,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "formulahendry.auto-rename-tag",
				"_lower": "formulahendry.auto-rename-tag"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Illegal value for `line`"
		}
	]
}
```

**Comment by alefragnani** [comment]
Hi @dadams63 ,

Could you give more details about what/how it happened? 

* What kind of workspace were you using:
- [ ] Single folder
- [ ] Multi-root folder
- [ ] no-folder

* What where you doing:
- [ ] typing
- [ ] navigation
- [ ] pasting content

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
