### ISSUE TITLE
Support contributes.colors

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-numbered-bookmarks#61]
As described here https://code.visualstudio.com/api/references/contribution-points#contributes.colors

Just like https://github.com/alefragnani/vscode-bookmarks/issues/246

**Comment by alefragnani** [comment]
This new feature will deprecate the `numberedBookmarks.backgroundLineColor` setting, which were introduced in version 5.2.0, via PR #44, being requested in #33 .

I thought about automatically migrate the setting, but I don't like to touch on user settings, specially when you have User, Workspace and Folder settings to take care of. Unfortunately, there is no API do know if a ThemeColor is defined, or which value it has, so I'm out of luck to know if the user has defined the color itself.

Just like on my other Bookmarks extension, I'll simply ignore the deprecated setting, and use the `workbench.colorCustomizations` value (if available). 

Since you, @ibraimgm and @Rah1x did participate in the original issues/PRs, I'm _pinging_ you 👀 . 

Enjoy the new release

ps. In newer releases, the `Icon` will also be theme able via `workbench.colorCustomizations`.

**Comment by Rah1x** [comment]
Thanks for tagging me cause otherwise I wouldnt have known without some look around how to set the bookmark colours. Now its just simply: `numberedBookmarks.lineBackground` inside `workbench.colorCustomizations`

**Comment by ibraimgm** [comment]
Nice! Thanks for the heads up!
