### ISSUE TITLE
Error in navigation when empty file open

### ISSUE THREAD

**Issue by dudeNumber4** [alefragnani/vscode-numbered-bookmarks#68]
- Mark a location in a file with some text.  Leave that tab open.
- Create a new empty file.  Attempt to navigate to the location you marked above.
Result: error appears.

**Comment by alefragnani** [comment]
Hi @dudeNumber4 ,

Good catch! 

BTW, if you want to _directly_ navigate to bookmarks located in other files using the shortcuts, I suggest you to take a look at `umberedBookmarks.navigateThroughAllFiles` setting first.  In its default behaviour (`false`) it would look for bookmarks on the current file, only.

### Possible Values:

Value | Explanation
--------- | ---------
`false` | _default_ - same behavior as today
`replace` | you can't have the same numbered bookmark in different files
`allowDuplicates` | you can have the same numbered bookmark in different files, and if you jump repeatedly to the same number, it will look on other files

Hope this helps
