### ISSUE TITLE
Add `setting` to decide if should display a message if N bookmark is not found

### ISSUE THREAD

**Issue by Daijobou** [alefragnani/vscode-numbered-bookmarks#73]
When I want jump to a bookmark thats not exists (anymore) in this file I get now every time a messagebox
![image](https://user-images.githubusercontent.com/260343/82087147-d13ce300-96ef-11ea-9a51-ab6e97867633.png)
Is here a way to prevent this? This is a little annoying. I do not understand the purpose of this message box.

**Comment by alefragnani** [comment]
Hi @Daijobou ,

This has changed in the latest release. Prior to this, this message was displayed in the Status Bar, maybe you didn’t noticed. 

I just changed to use the same location other Info/error messages are displayed, like `No bookmark found`. TBH, I’m not sure why it was using the Status Bar. 

There is no way to prevent this message from appearing, as hasn’t before this change. Unless you think no message at all should be displayed, if you try to jump to some _undefined/untoggled_ bookmark. It could be added via `settings`.

Hope this helps

**Comment by Daijobou** [comment]
I have many bookmarks in many files, because its so helpful, but its happen often that bookmarks not exists because code changed. Now I get for this a messagebox that I must close. I don't need a messagebox that said there is not bookmark, because I see that there is no bookmark. So I dont see any meaning in this box. Bacause "Delphi style". In Delphi is no messagebox for undefined bookmarks. ;)

**Comment by alefragnani** [comment]
> Because "Delphi style". In Delphi is no messagebox for undefined bookmarks. ;)

Good point 😆

**Comment by Daijobou** [comment]
I guess the change did not make it into version 7.2.0?

**Comment by alefragnani** [comment]
Hi @Daijobou ,

No, it didn't, sorry. I ended up closing the release with features that I wanted to finish on some of my extensions, and decided not to wait for that.

But it will be on the next one, which should be released next week.

Stay tuned
