### ISSUE TITLE
Ability to navigate to bookmarks in other files

### ISSUE THREAD

**Issue by NikosEfthias** [alefragnani/vscode-numbered-bookmarks#8]
i cannot reach bookmarks from other files opened how can i make bookmarks project wide available

**Comment by alefragnani** [comment]
The bookmarks _file based_, numbered from 1 to 9 for each file, so using the `Jump to Bookmark _N_` will only work for the current file. Also the `List` command only shows bookmarks for the _current file_. 

But maybe a new command `List All` should be added, showing all the bookmarks, from all files.

**Comment by alefragnani** [comment]
Duplicate of #3

**Comment by alefragnani** [comment]
Hi @NikosEfthias
Just released version 0.5.0 with this feature. Give it a try 😄
