### ISSUE TITLE
[FEATURE] - Allow setting bookmarks via context menu

### ISSUE THREAD

**Issue by Bu11etmagnet** [alefragnani/vscode-numbered-bookmarks#84]
I'd like to set, clear (or just one action, toggle) and jump to bookmarks from the context menu.
This is a revival of #9 , which I can't reopen.
The vscode issue it depends on, microsoft/vscode#9827, was marked Closed(Fixed) on 2020-09-01.

**Comment by alefragnani** [comment]
Hi @Bu11etmagnet ,

That's true! Starting on recent releases, it is now possible to create **Submenus**.

Thanks for (re)opening

**Comment by alefragnani** [comment]
Opened this issue (https://github.com/microsoft/vscode/issues/114110), because the shortcuts are being drawn incorrectly.
