### ISSUE TITLE
Commands in context menu

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-numbered-bookmarks#9]
Two commands, each one containing the 10 numbered bookmarks:
- `Toggle Bookmarks`
- `Go to Bookmarks`

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/9827

**Comment by ericblade** [comment]
I wouldn't be opposed to having either a single bookmark toggleable and returnable from the menu, or having 10 menu items to get all of them :-)

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.
