### ISSUE TITLE
[ENCHANCEMENT] - Sync settings color with scroll bar color

### ISSUE THREAD

**Issue by drackp2m** [alefragnani/vscode-numbered-bookmarks#90]
Basically I think it would be interesting to see the fill colors of the icon next to the line number synchronized with the mark that appears in the scroll bar.

Or else, an option where you could choose the color of this visual aid.

Edit: sorry, this is not a bug.

**Comment by alefragnani** [comment]
Hi @drackp2m ,

You already have an option for that, the same way you can customize the line `border` and `background`, using **Color Customisations**. More info here: https://github.com/alefragnani/vscode-numbered-bookmarks#available-colors.

Just add something like this on your user settings:

```json
    "workbench.colorCustomizations": {
      "numberedBookmarks.overviewRuler": "#157EFB88"  
    }
```

Hope this helps
